version: "3.8"
services:
    client:
        build:
            context: .
        volumes: 
            - type: bind
              source: .
              target: /app
            - type: volume
              target: /app/node_modules
        ports:
            - 4200:4200